### ISSUE TITLE
Improve server controls & tooltips UI

### ISSUE THREAD

**Issue by LostInStatic** [vnLab-Lodz/PubLab#252]
## Description

This issue serves mainly as a reminder to brainstorm solutions (or decide not to) to following issues:
 - Terminal window in sideview might be too small for some cases. Additionally, if the user does not want it to be visible, having an option to control a server without clicking 'keep visible' button would be convenient.
 - Installing dependencies can take a long time without any message in the terminal. This might be confusing, especially for a first-time user.
 - A button to manually open the website in the browser would be useful, if the user closes the browser tab by accident.
 - Immediate tooltips can be annoying if the controls are in vertical arrangement. Maybe a (configurable?) delay should be implemented?

**Comment by karczewskiPiotr** [comment]
@LostInStatic I will come through later on today to give my thoughts on the points above.

**Comment by karczewskiPiotr** [comment]
> Terminal window in sideview might be too small for some cases. Additionally, if the user does not want it to be visible, having an option to control a server without clicking 'keep visible' button would be convenient.

@LostInStatic I agree that it might be worth to add a toggle to the server if the user does not want to see it at all times. We should be careful with how we achieve that though. Any way that will rerender the component will mean that we lose the previous output unless we store the _session_ in the back-end, which would mean an unnecessary time expenditure. If we can achive such toggling with CSS on some outside element we should be good. We might also need to think of a way to let the user know that the server is still running when it has been toggled to the invisible state.

The terminal window is quite small but it's rather a thing that the user might take a screenshot of to send to the developer rather than something they will read stuff from. I do not think anyone will pay much attention to the dev jibberish showing up in there untill something goes wrong with the local environment for them.

> Installing dependencies can take a long time without any message in the terminal. This might be confusing, especially for a first-time user.

I guess we could set an interval to show some messages to indicate that things are still installing if the amount of time since the last message shown is bigger than 10 seconds or something like that.

> A button to manually open the website in the browser would be useful, if the user closes the browser tab by accident.

I'm not sure if this is a real problem. If the user accidentally closes the website they can just use the browser function to restore last page or whatever. Otherwise we would have to send the captured localhost uri to the state and enable the button to open the website with it as the dev url might be set to different ports by different teams for example. Not fully convinced that this is a problem worth solving.

> Immediate tooltips can be annoying if the controls are in vertical arrangement. Maybe a (configurable?) delay should be implemented?

You mean like horizontal above the server? We could totally set a delay on them to not show immediately when going to the last control element and that. MUI has a built in prop for that so we can pass in some reasonable value.

**Comment by LostInStatic** [comment]
> @LostInStatic I agree that it might be worth to add a toggle to the server if the user does not want to see it at all times. We should be careful with how we achieve that though. Any way that will rerender the component will mean that we lose the previous output unless we store the _session_ in the back-end, which would mean an unnecessary time expenditure. If we can achive such toggling with CSS on some outside element we should be good. We might also need to think of a way to let the user know that the server is still running when it has been toggled to the invisible state.

Do you think putting the entire side view on a similar slide-in animation as the one on the main menu could be a solution? Maybe toggled by a small button somewhere instead of on hover (I'm not sure what would be better)?

> I'm not sure if this is a real problem. If the user accidentally closes the website they can just use the browser function to restore last page or whatever. Otherwise we would have to send the captured localhost uri to the state and enable the button to open the website with it as the dev url might be set to different ports by different teams for example. Not fully convinced that this is a problem worth solving.

Sure, let's leave it if it requires more work than just adding a button. Maybe it's just me 😆 

> You mean like horizontal above the server? We could totally set a delay on them to not show immediately when going to the last control element and that. MUI has a built in prop for that so we can pass in some reasonable value.

I stumbled upon it while adding the tooltips to the project creation wizard: 
![electron_NR8KjiDQJu](https://user-images.githubusercontent.com/23729453/202320859-c9db07e8-a44a-4caf-940f-92d4b6cc2485.gif)

However, when I look at it now, changing the position seems an obvious solution:
![image](https://user-images.githubusercontent.com/23729453/202320995-45237b16-66b5-4668-bff2-0c1a6d460492.png)

Do you think we should add a delay anyway, or lets just adjust the positioning and call it a day?

**Comment by karczewskiPiotr** [comment]
> Do you think putting the entire side view on a similar slide-in animation as the one on the main menu could be a solution? Maybe toggled by a small button somewhere instead of on hover (I'm not sure what would be better)?

@LostInStatic  oh I was thinking about just the terminal but making an entire side view collapsible might make a lot of sense for smaller screen users that still want quick access to those features. I would lean towards a button rather than an implementation similair to the primary sidebar. I doubt many people would actually figure out that left sidebar can be kept open.

> Do you think we should add a delay anyway, or just adjust the positioning and call it a day?

ah these ones, right. Changing the position would make a lot of sense. Does it come with that weird MUI thing were the border flashes in certain positions of the tooltip though?

**Comment by LostInStatic** [comment]
@karczewskiPiotr 
> @LostInStatic oh I was thinking about just the terminal but making an entire side view collapsible might make a lot of sense for smaller screen users that still want quick access to those features. I would lean towards a button rather than an implementation similair to the primary sidebar. I doubt many people would actually figure out that left sidebar can be kept open.

I put together an implementation.

> ah these ones, right. Changing the position would make a lot of sense. Does it come with that weird MUI thing were the border flashes in certain positions of the tooltip though?

AFAIK not in this case, tested it couple of times.
